### ISSUE TITLE
Add padding zeroes (0) and underscores (_) to file names

### ISSUE THREAD

**Issue by phongvcao** [chrisdcao/Algos_4th_Solutions#1]
It's better to add padding zeroes (0) and undercores (_) to file names to make it clearer which exercises are which. For example, [ex1111.cc](https://github.com/chrisdcao/Algos_4th_Solutions/blob/db97f19f7b5863c2c777a9d1f056715a8a8f4f72/Chapter_1/ex1111.cc#L1) - it's better to be written as ex_01_01_11.cc (which padding zeroes) so Github would sort the exercises accordingly.

**Comment by chrisdcao** [comment]
Yessss
